### ISSUE TITLE
Running dan Jump Animation

### ISSUE THREAD

**Issue by L200160067** [L200160067/HappyTrigger#11]

**Comment by Arifinsetya** [comment]
Sudah saya taruh Attack, Die, Hurt, Idle, Jump LookUp, Run. Di folder Animations->Player. Biar bisa dilihat Animasi nya drag Player di hierarcy ke inspector animation yg ada di folder Player, Lalu play

**Comment by bsrmdn** [comment]
Jika yang dimaksud animasi untuk player sudah saya tambahkan
