### ISSUE TITLE
Buatkan saya Parallax untuk Background dsb..

### ISSUE THREAD

**Issue by Arifinsetya** [L200160067/HappyTrigger#9]
Saya bingung coding parallax. 

contoh:
![Parallax_scroll](https://github.com/L200160067/HappyTrigger/assets/112671477/d15be175-29d0-45af-9488-6a39a9e6b291)

**Comment by L200160067** [comment]
link ga gbisa di akses

**Comment by Arifinsetya** [comment]
> link ga gbisa di akses

Dah saya update
